# Generated by Django 5.2.3 on 2025-06-11 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercadoria',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mercadorias.setor'),
        ),
    ]
